package jun.watson.entity

enum class ItemEntityType {

    DESTINY_DESTRUCTION_STONE,
    REFINED_OBLITERATION_STONE,
    OBLITERATION_STONE,
    DESTRUCTION_STONE_CRYSTAL,

    DESTINY_GUARDIAN_STONE,
    REFINED_PROTECTION_STONE,
    PROTECTION_STONE,
    GUARDIAN_STONE_CRYSTAL,

    DESTINY_SHARD,
    HONOR_SHARD,

    DESTINY_LEAPSTONE,
    RADIANT_HONOR_LEAPSTONE,
    MARVELOUS_HONOR_LEAPSTONE,
    GREAT_HONOR_LEAPSTONE

}
