spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  liquibase:
    enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

api:
  keys:
    key1: ${API_KEY_1}
    key2: ${API_KEY_2}
    key3: ${API_KEY_3}
    key4: ${API_KEY_4}